#!/usr/bin/env python3
"""
dgc.py - Simple context packer for Claude Code
Scans your project, finds the most relevant files, and pre-loads them
into a CLAUDE_CONTEXT.md so Claude spends tokens solving — not exploring.

Usage (Windows):
    python dgc.py                              # scan + asks what to do
    python dgc.py --context-only               # just create CLAUDE_CONTEXT.md
    python dgc.py --launch                     # create file + launch Claude
    python dgc.py --launch "fix the login bug" # create file + launch with prompt
    python dgc.py C:\path\to\project --launch  # specific project

Usage (Linux / macOS):
    chmod +x dgc.py && sudo cp dgc.py /usr/local/bin/dgc
    dgc                                        # scan + asks what to do
    dgc --context-only                         # just create CLAUDE_CONTEXT.md
    dgc --launch                               # create file + launch Claude
    dgc /path/to/project --launch "add tests"  # specific project + prompt
"""

import os
import sys
import subprocess
from pathlib import Path

# ── Config ─────────────────────────────────────────────────────────────────────
MAX_FILES       = 40       # max files to include in context
MAX_FILE_CHARS  = 3000     # max characters read per file
MAX_TOTAL_CHARS = 50_000   # total context budget
CONTEXT_FILE    = "CLAUDE_CONTEXT.md"

SKIP_DIRS = {
    "node_modules", ".git", "__pycache__", ".venv", "venv", "env",
    "dist", "build", ".next", ".nuxt", "coverage", ".cache",
    ".dual-graph", ".idea", ".vscode",
}

CODE_EXTS = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java",
    ".kt", ".cs", ".rb", ".php", ".c", ".cpp", ".swift", ".vue",
    ".html", ".css", ".scss", ".json", ".yaml", ".yml", ".toml",
    ".env", ".sh", ".ps1", ".md",
}

IMPORTANT_NAMES = {
    "main", "index", "app", "server", "config", "settings",
    "routes", "api", "auth", "db", "database", "models", "schema",
    "utils", "helpers", "types", "constants",
}


# ── File scanning ──────────────────────────────────────────────────────────────
def should_skip(path: Path) -> bool:
    for part in path.parts:
        if part in SKIP_DIRS or part.startswith("."):
            return True
    return False


def score_file(path: Path, root: Path) -> int:
    score = 0
    stem = path.stem.lower()
    rel = str(path.relative_to(root))

    if stem in IMPORTANT_NAMES:
        score += 30

    depth = len(path.relative_to(root).parts)
    score += max(0, 10 - depth * 2)

    try:
        size = path.stat().st_size
        if size < 5_000:
            score += 10
        elif size > 50_000:
            score -= 10
    except Exception:
        pass

    if any(p in rel.lower() for p in ["config", "setting", "env", "route", "api"]):
        score += 15

    return score


def scan_project(root: Path) -> list:
    files = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if should_skip(path.relative_to(root)):
            continue
        if path.suffix.lower() not in CODE_EXTS:
            continue
        files.append(path)
    files.sort(key=lambda p: score_file(p, root), reverse=True)
    return files[:MAX_FILES]


# ── Context builder ────────────────────────────────────────────────────────────
def read_file_snippet(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        if len(text) > MAX_FILE_CHARS:
            text = text[:MAX_FILE_CHARS] + f"\n... (truncated, {len(text)} chars total)"
        return text
    except Exception as e:
        return f"(could not read: {e})"


def build_context(root: Path, files: list) -> str:
    lines = [
        f"# Project Context: {root.name}",
        f"Root: {root}",
        "",
        "## File Tree (relevant files)",
        "```",
    ]
    for f in files:
        rel = f.relative_to(root)
        indent = "  " * (len(rel.parts) - 1)
        lines.append(f"{indent}{rel.parts[-1]}")
    lines += ["```", ""]

    total_chars = 0
    included = 0
    for f in files:
        snippet = read_file_snippet(f)
        block_size = len(snippet) + 100
        if total_chars + block_size > MAX_TOTAL_CHARS:
            lines.append(f"\n*(context budget reached — {len(files) - included} files omitted)*")
            break
        rel = str(f.relative_to(root))
        lines += [
            f"## {rel}",
            f"```{f.suffix.lstrip('.')}",
            snippet,
            "```",
            "",
        ]
        total_chars += block_size
        included += 1

    lines += [
        "---",
        "*Generated by dgc.py — edit CLAUDE_CONTEXT.md to add notes for Claude.*",
    ]
    return "\n".join(lines)


def detect_project_type(root: Path) -> str:
    markers = {
        "package.json":    "Node.js / JavaScript",
        "pyproject.toml":  "Python",
        "requirements.txt":"Python",
        "go.mod":          "Go",
        "Cargo.toml":      "Rust",
        "pom.xml":         "Java (Maven)",
        "build.gradle":    "Java (Gradle)",
    }
    for marker, label in markers.items():
        if (root / marker).exists():
            return label
    if list(root.glob("*.csproj")):
        return ".NET / C#"
    return "Unknown"


# ── Launch Claude ──────────────────────────────────────────────────────────────
def launch_claude(root: Path, prompt: str = ""):
    claude_cmd = ["claude"]
    if prompt:
        claude_cmd += ["--print", f"Using the context in {CONTEXT_FILE}: {prompt}"]
    print(f"[dgc] Launching Claude Code...")
    try:
        os.chdir(root)
        subprocess.run(claude_cmd, check=False)
    except FileNotFoundError:
        print("[dgc] Error: 'claude' not found. Install it with:")
        print("       npm install -g @anthropic-ai/claude-code")
        sys.exit(1)


# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    args = sys.argv[1:]

    # Parse flags
    context_only = "--context-only" in args
    do_launch    = "--launch" in args
    args = [a for a in args if a not in ("--context-only", "--launch")]

    # Parse path + prompt from remaining args
    project_path = "."
    prompt = ""
    if args:
        if Path(args[0]).exists() or args[0] == ".":
            project_path = args[0]
            prompt = " ".join(args[1:])
        else:
            prompt = " ".join(args)

    root = Path(project_path).resolve()
    if not root.is_dir():
        print(f"[dgc] Error: '{root}' is not a directory.")
        sys.exit(1)

    # Scan
    print(f"[dgc] Scanning {root.name}...")
    proj_type = detect_project_type(root)
    print(f"[dgc] Project type: {proj_type}")
    files = scan_project(root)
    print(f"[dgc] Found {len(files)} relevant files to pre-load")

    # Write context file
    context = build_context(root, files)
    summary = f"# Project: {root.name}\nType: {proj_type}\nFiles scanned: {len(files)}\n\n"
    context_path = root / CONTEXT_FILE
    context_path.write_text(summary + context, encoding="utf-8")
    size_kb = context_path.stat().st_size / 1024
    print(f"[dgc] Context written → {CONTEXT_FILE} ({size_kb:.1f} KB)")
    print(f"[dgc] Estimated tokens saved: ~30-40% per session")

    # Decide what to do next
    if context_only:
        print("[dgc] Done. Open CLAUDE_CONTEXT.md to review, then run 'claude' when ready.")
        return

    if do_launch:
        launch_claude(root, prompt)
        return

    # No flag given — ask interactively
    print()
    print("What would you like to do?")
    print("  1) Just created the context file (done)")
    print("  2) Create the context file + launch Claude now")
    choice = input("Enter 1 or 2: ").strip()

    if choice == "2":
        if not prompt:
            prompt = input("Starting prompt for Claude (optional, press Enter to skip): ").strip()
        launch_claude(root, prompt)
    else:
        print(f"[dgc] Done. Run 'claude' in {root.name} when you're ready.")


if __name__ == "__main__":
    main()
